vim.keymap.set('n', '<leader><space>', ':nohlsearch<CR>')
vim.keymap.set('n', '<leader><tab>', 'za')
vim.keymap.set('n', 'th', ':tabprev<CR>')
vim.keymap.set('n', 'tl', ':tabnext<CR>')
vim.keymap.set('n', 'td', ':tabclose<CR>')
vim.keymap.set('n', 'gh', '<C-W>h')
vim.keymap.set('n', 'gl', '<C-W>l')
vim.keymap.set('n', 'gk', '<C-W>k')
vim.keymap.set('n', 'gj', '<C-W>j')
vim.keymap.set('v', '.', ":'<,'>call funtions#Repeat_with_visual_selection()<CR>")
vim.keymap.set('v', '<C-r>', '"hy:%s/<C-r>h//gc<left><left><left>')
vim.keymap.set('n', '<C-6>', '<C-^>')
vim.keymap.set('n', '<C-t>', '<cmd>tabnew %<CR>')
