return {
  colors = require('plugins.heirline.components.colors'),
  vim_mode = require('plugins.heirline.components.vim-mode'),
  file_name = require('plugins.heirline.components.file-name'),
  short_file_name = require('plugins.heirline.components.short-filename'),
  filetype = require('plugins.heirline.components.filetype'),
  ruler = require('plugins.heirline.components.ruler'),
  lsp = require('plugins.heirline.components.lsp'),
  git = require('plugins.heirline.components.git'),
  cwd = require('plugins.heirline.components.working-directory'),
  terminal_name = require('plugins.heirline.components.terminal-name'),
  spell = require('plugins.heirline.components.spell'),
  macro_rec = require('plugins.heirline.components.macro-rec'),
  search_count = require('plugins.heirline.components.search-count'),
  utils = require('plugins.heirline.components.utils'),
}
