Cesar.require('lazydev', {
  opts = {
    library = {
      -- See the configuration section for more details
      -- Load luvit types when the `vim.uv` word is found
      { path = '${3rd}/luv/library', words = { 'vim%.uv' } },
      'lazy.nvim',
      'snacks.nvim',
      'smart-splits.nvim',
      'mini.nvim',
      'gitsings.nvim',
      'blink-cmp-spell',
      'blink.cmp',
      'catppuccin',
      -- 'codediff.nvim',
      -- 'colorful-menu.nvim',
      'conform.nvim',
      'copy-path.nvim',
      'diffview.nvim',
      'fidget.nvim',
      -- 'friendly-snippets',
      'inline-diff.nvim',
      -- 'lazydev.nvim',
      -- 'lsp-progress.nvim',
      'mason-tool-installer.nvim',
      'mason.nvim',
      -- 'meow.yarn.nvim',
      'neo-tree.nvim',
      'neogit',
      'nui.nvim',
      -- 'nvim-bqf',
      'nvim-lspconfig',
      'nvim-metals',
      'nvim-pqf',
      'nvim-treesitter',
      -- 'nvim-window-picker',
      'plenary.nvim',
      -- 'toggle-checkbox.nvim',
      -- 'vim-fugitive',
      'which-key.nvim',
    },
  }
})
